services:
  eth-bot:
    build: .
    restart: always
    command: python src/core/main.py
    environment:
      - PYTHONPATH=/app/src
    volumes:
      - .:/app
    env_file:
      - .env

  admin-bot:
    build: .
    restart: always
    command: python src/utils/admin_bot.py
    environment:
      - PYTHONPATH=/app/src
    volumes:
      - .:/app
    env_file:
      - .env